// Developer environment
require('dotenv').config();

// main parameters for Lambda.
const eventRepeatIntent = {
  version: '1.0',
  session: {
    new: false,
    sessionId: 'amzn1.echo-api.session.00aa000a-a000-00a0-a0aa-aa00aa000000',
    application: {
      applicationId: 'amzn1.ask.skill.a0a0000a-00a0-00a0-0000-0aaaaa000a00',
    },
    user: {
      userId: 'amzn1.ask.account.ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXY',
    },
  },
  context: {
    System: {
      application: {
        applicationId: 'amzn1.ask.skill.a0a0000a-00a0-00a0-0000-0aaaaa000a00',
      },
      user: {
        userId: 'amzn1.ask.account.ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXY',
      },
      device: {
        deviceId: 'amzn1.ask.device.AGWX3F567ZLCNRKK3EWONQGBNQTCECXFU6JSSNSIT3UJ2URGCJ7AHBINCJ6SNRMBSA2AIUOLET25T6JJKU5UHKRQMF4Q3OE475FW47WRUKHFKCECUIP2B6BUGBNKOA765Y3CJWKRVRRYD6VAO2NFUKUF2UJA',
        supportedInterfaces: {},
      },
      apiEndpoint: 'https://api.fe.amazonalexa.com',
      apiAccessToken: 'ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX.YZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJ.KLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZAB-CDEFGHIJKLMNO-PQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKL',
    },
  },
  request: {
    type: 'IntentRequest',
    requestId: 'amzn1.echo-api.session.00aa000a-a000-00a0-a0aa-aa00aa000000',
    timestamp: '2018-04-06T04:06:46Z',
    locale: 'ja-JP',
    intent: {
      name: 'AMAZON.RepeatIntent',
      confirmationStatus: 'NONE',
    },
  },
};

const event = eventRepeatIntent;
const context = {};

// const lambda = require('./build/index');
const lambda = require('./src/index');

// Execute.
console.time('execute lambda.handler');
lambda.handler(event, context)
  .then(data => console.log(`Process complete successfully. Returned value is below.\r\n${data}`))
  .catch(e => console.error(e))
  .finally(() => console.timeEnd('execute lambda.handler'));
